Repository wp-cli/i18n-command, pull requests merged in 2018-08, with the labels that each got.

#56 Print some more helpful debug messages
  features/makepot.feature
  src/MakePotCommand.php
Labels: command:i18n-make-pot

#67 Adapt to new test system
  .travis.yml
  bin/install-package-tests.sh
  bin/test.sh
  composer.json
  features/bootstrap/FeatureContext.php
  features/bootstrap/Process.php
  features/bootstrap/ProcessRun.php
  features/bootstrap/support.php
  features/bootstrap/utils.php
  features/extra/no-mail.php
  features/makepot.feature
  features/steps/given.php
  features/steps/then.php
  features/steps/when.php
  utils/behat-tags.php
Labels: scope:distribution, scope:testing

#64 Check for more mistakes in translatable strings
  features/makepot.feature
  src/MakePotCommand.php
Labels: command:i18n-make-pot

#69 WordPress Core support
  README.md
  features/makepot.feature
  src/IterableCodeExtractor.php
  src/MakePotCommand.php
Labels: command:i18n-make-pot

#72 Prepare for v2 release
  composer.json
Labels: scope:distribution

#74 Add Composer config settings
  composer.json
Labels: scope:distribution

#78 fix deps and composer normalize
  composer.json
Labels: scope:distribution
