Repository wp-cli/i18n-command, pull requests merged in 2019-04, with the labels that each got.

#152 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#155 CS: clean up after merges
  src/PotGenerator.php
Labels: command:i18n

#159 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#156 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  phpcs.xml.dist
  src/IterableCodeExtractor.php
  src/MakeJsonCommand.php
  src/MakePotCommand.php
Labels: command:i18n

#161 Fine-tune property and variable name whitelisting
  phpcs.xml.dist
  src/JsFunctionsScanner.php
  src/MapCodeExtractor.php
  src/PhpFunctionsScanner.php
Labels: scope:testing

#162 Update README.md file
  README.md
Labels: scope:documentation
