Repository wp-cli/i18n-command, pull requests merged in 2019-08, with the labels that each got.

#149 Fix: Warning: strpos(): Empty needle
  src/IterableCodeExtractor.php
Labels: bug, command:i18n-make-pot

#178 Skip broken test on PHP 7.3
  features/makepot.feature
Labels: command:i18n-make-pot, scope:testing

#175 Investigate include/exclude oddities
  .gitignore
  src/IterableCodeExtractor.php
  tests/IterableCodeExtractorTest.php
  tests/data/vendor/vendor-file.php
Labels: command:i18n-make-pot, help-wanted
