Repository wp-cli/i18n-command, pull requests merged in 2020-04, with the labels that each got.

#207 Add option `--skip-php` to `i18n make-pot` command
  features/makepot.feature
  src/MakePotCommand.php
Labels: command:i18n-make-pot

#206 Fix Travis CI `sudo` warning
  .travis.yml
Labels: scope:distribution

#208 Enforce PHP 7.4 compatibility in Travis CI
  .travis.yml
Labels: scope:testing

#209 Bump Travis CI OS from `trusty` to `xenial`
  .travis.yml
Labels: scope:testing
